[project]
name = "psoriasis-food-scout"
version = "0.1.0"
description = "Food dietary suggestions for psoriasis or scalp psoriasis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
    "google-genai>=1.31.0",
    "flask>=3.0.0",
    "pillow>=10.0.0"
]

